# Generated by Django 2.1 on 2018-08-29 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('production_year', models.IntegerField()),
                ('mileage_start', models.IntegerField()),
                ('mileage_end', models.IntegerField()),
                ('plate_number', models.CharField(max_length=10)),
                ('color', models.CharField(max_length=20)),
                ('location_id', models.CharField(max_length=50)),
                ('status', models.BooleanField(default=True)),
                ('brand', models.CharField(max_length=15)),
                ('models', models.CharField(max_length=10)),
            ],
        ),
    ]
